name: mobile_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  intl: ^0.18.1 





dev_dependencies:
  flutter_test:
    sdk: flutter

  provider: ^6.1.1 


  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9



  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600


  uses-material-design: true

  assets:
    - assets/
    - assets/home.png
    - assets/surgeon.png
    - assets/lab.png
    - assets/nurse.png
    - assets/swipper1.png
    - assets/app.png
    - assets/precious.png
    - assets/care.png
    - assets/joint.png
    - assets/diabetes.png
    - assets/pain.png
    - assets/condition.png
    - assets/profile.png
    - assets/cal.png
    - assets/product1.PNG
    - assets/product2.PNG
    - assets/product3.PNG
    - assets/product4.PNG
    - assets/product11.PNG
    - assets/product12.PNG
    - assets/category1.png
    - assets/category2.png
    - assets/category3.png
    - assets/category4.png
    - assets/category5.png
    - assets/category6.png
    - assets/Vector.png
    - assets/rx.png
    - assets/chat.png
    - assets/call.png
    - assets/profile1.png
    - assets/icon.png
    - assets/product.png
    - assets/vector_copy.png
    - assets/profile2.png
    - assets/profile3.png
    - assets/profile4.png
    - assets/left.png
    - assets/chain.png
    - assets/food_image.png
    - assets/profile5.png
    - assets/profile6.png











